name: Validate SDK Distribution

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Check Installed Gems
        run: bundle list

      - name: Run Pre-Commit Validator
        run: |
          # Make sure the script is executable
          chmod +x Scripts/git/pre-commit-validator.rb

          # Run the validation script
          bundle exec ruby Scripts/git/pre-commit-validator.rb
